name: "craftattack"

main: org.legenddragon.craftattack.craftattack
version: 1.3
api-version: 1.16

author: "LegendDragon11"
description: "Dies ist ein Craftattack Plugin"

permissions:
  server.settings:
    description: "A permission to edit Server configurations, like the lockmode"
  enderchest.open:
    description: "Let the Player open EnderChest from another Player"
  invsee:
    description: "Let the Player see into a Inventory from another Player"

commands:
  tpa:
    description: "Teleport a Player to another."
  lock:
    description: "A Command to manage some Server settings."
  pos:
    aliases: "p"
    description: "A Command to save positions in minecraft"
  ec:
    description: "A Command to open your enderchest imedialtly"
  inv:
    description: "A Command to open another inventory"
  spawn:
    description: "Teleports Player to Spawn"
  stats:
    description: "Shows some Minecraft Statistics"